version: '2.1'
services:
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./apache:/usr/local/apache2/htdocs/
  nginx:
    image: nginx:1.21
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/usr/share/nginx/html/
